### ISSUE TITLE
Increase Character in Password Generator

### ISSUE THREAD

**Issue by Taufiq-HxH** [yogeshpaliyal/KeyPass#10]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
Increase the characters in creating a password so that the resulting password is stronger

**Describe alternatives you've considered**
None

**Additional context**
User can choose whether to increase or decrease the characters in password generator

**Comment by yogeshpaliyal** [comment]
@Taufiq-HxH Thanks for the feedback
In next update will provide an option to customize password length.

**Comment by yogeshpaliyal** [comment]
Added in new build v1.3.5
Live on play store
