### ISSUE TITLE
Authentication Error, Authentication Failed

### ISSUE THREAD

**Issue by DigitalNXZ** [yogeshpaliyal/KeyPass#12]
**Describe the bug**

**To Reproduce**
1. Open 'KeyPass'
2. Wait 'It shows instantly a error, than draw your pw'
3. "it shows, failed again and shows enter keypass screen, and than I need to draw my Password again.. than im in"

**Expected behavior**

Should Open Without a error

**Screenshots**

GitHub doesnt acces my gallery.. well
[https://i.imgur.com/7mHMK1q.jpg](https://i.imgur.com/7mHMK1q.jpg) 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - Mi 9T Pro
 - OS: [e.g. iOS8.1] - Android 10 + MIUI 12
 - Version [e.g. 22] - 1.3.5

**Additional context**

**Comment by yogeshpaliyal** [comment]
Can you provide a video if possible

**Comment by DigitalNXZ** [comment]
It doesnt happen since the update to Android 11 I did a few days ago it
doesnt happen anymore, im sorry I think the issue can get closed

~best regards

**Comment by yogeshpaliyal** [comment]
Thanks for your feedback
