### ISSUE TITLE
Keepass 

### ISSUE THREAD

**Issue by Raif1** [yogeshpaliyal/KeyPass#120]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an option to use kdbx files or keepass type files to use as database . So then we will be able to use this app as keepass for android application which will be very nice . And the ui is great. 

**Describe alternatives you've considered**
Many keepass android implementations Keepassdx keepass2android etc. 

**Additional context**

**Comment by IJR222** [comment]
This is a duplicate of #47
