### ISSUE TITLE
Multiple Features

### ISSUE THREAD

**Issue by DigitalNXZ** [yogeshpaliyal/KeyPass#13]
**Is your feature request related to a problem? Please describe.**

1. Would it be possible to add an add to Clipboard Button? or copying it by long pressing? (idk if this would make sense at all and if its dangerous.. since you must copy it anyways and clipboard isnt the safest anyway)
2. There is a Password Gen, would it be possible to add the Password Gen settings to Add Acc? like there is a gen but it only creates password with a lenght of 7
3. May a setting where you can set the cards on the bottom? from bottom to top and not just from top to button list?

I think thats all.

**Describe the solution you'd like**
1. On the right side an Icon that indicates that you can copy your password by clicking it, or simply a little menu when you do a long click
2. Setting a template over the password gen tab that's get used for new Accounts/Cards and or some setitings to change the Password Gen sett. while you add an Card

**Describe alternatives you've considered**

**Additional context**

**Comment by AJS101** [comment]
I see that the clipboard can already by used in the current F-droid release.  While obviously very convienient I just thought I'd point out this apparently gaping hole in android clipboard security:
https://github.com/grepx/android-clipboard-security

Perhaps a warning message when attempted and/or disable by default to prevent unwitting users compromising the purpose of using a password manager?

**Comment by yogeshpaliyal** [comment]
Password generator and copy to clipboard option added. Thanks @DigitalNXZ
