### ISSUE TITLE
Error when trying to restore from backup

### ISSUE THREAD

**Issue by OOLEHLEH** [yogeshpaliyal/KeyPass#147]
**Describe the bug**
Error when trying to restore from backup

**To Reproduce**
1. Attempt to restore encrypted backup in settings

**Expected behavior**
Backup restores without error

**Screenshots**
![Screenshot_20220403-233729_KeyPass.jpg](https://user-images.githubusercontent.com/71150211/161469922-bf536dc6-5f00-45e4-8786-2b74f745f576.jpg)

**Smartphone (please complete the following information):**
 - Device: S20 FE
 - OS: Android 12 (One UI 4.0)
 - Browser: Firefox Nightly

**Additional context**
This happened when i reinstalled the app

**Comment by yogeshpaliyal** [comment]
@OOLEHLEH can you try with creating one more backup and then restoring that please.

**Comment by OOLEHLEH** [comment]
> @OOLEHLEH can you try with creating one more backup and then restoring that please.

So I tried and the new backup restored fine, The old backup was still getting the same error though.
