### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by linsui** [yogeshpaliyal/KeyPass#15]
**Describe the bug**
https://maven.localazy.com/repository/release/ is not a trusted maven repo. If Localazy is foss we need to build it from source. Could you please take a look? Thanks!

**Comment by yogeshpaliyal** [comment]
okay, thanks for your feedback, i have to remove that

**Comment by yogeshpaliyal** [comment]
It's removed

**Comment by linsui** [comment]
Thanks!
