### ISSUE TITLE
Update App Version on F-Droid

### ISSUE THREAD

**Issue by ivanov17** [yogeshpaliyal/KeyPass#18]
Please, update the application in the F-Droid repository. 

The current version on Google play is 1.3.7, and the version on F-Droid is 1.3.5. Also, the old version on F-Droid has a nasty bug with Android 11: entries are not saving, and no entries can be added after the installation. 

Thank you.

**Comment by yogeshpaliyal** [comment]
@ivanov17 sorry for the inconvenience, #15 has been resolved
