### ISSUE TITLE
Make a release of your application so we can test it. 

### ISSUE THREAD

**Issue by ghost** [yogeshpaliyal/KeyPass#223]
**Is your feature request related to a problem? Please describe.**

By looking at your commits history it seems you are doing 
a lot of work on Keypass. However, currently there is no possibility to test your lastest changes because you did not provide an .apk yet. 

**Describe the solution you'd like**

Please provide an apk so we can test your lastest changes. :)

**Comment by yogeshpaliyal** [comment]
Added
