### ISSUE TITLE
App is not responding; 

### ISSUE THREAD

**Issue by thatisnotmyname** [yogeshpaliyal/KeyPass#29]
The app is crashing all the time when I try to see password. It checks my touch or face identity, it shows me list of my credentials, but when I try to see any of them, immediately crashes and goes out. I recently updated to the new version and now I can't even to downgrade because of some error. Is there any solution? Thanks.

**Comment by thatisnotmyname** [comment]
Latest Version 1.3.9

**Comment by yogeshpaliyal** [comment]
Currently there is no option to see logs, but i will check updating app from v1.3.8 to v.13.9
