### ISSUE TITLE
Mono font for passwords

### ISSUE THREAD

**Issue by Rvolvr** [yogeshpaliyal/KeyPass#295]
My Android has a modern font for all fields when looking through KeyPass. Would it be possible to force `console type fonts` when viewing saved passwords?

I copy a password into a terminal emulator to tell the difference between certain characters.

**Comment by yogeshpaliyal** [comment]
Can you please share a sample video or screenshot for the same

**Comment by Rvolvr** [comment]
Here is a screenshot from my phone. ![Screenshot_20230113-081808.png](https://user-images.githubusercontent.com/10343946/212354894-53063694-05b8-41a5-8fac-5537eed5dc6e.png)

The password is 
```
Il|O0o'`,.
```
