### ISSUE TITLE
Add import kdbx files from keepass please.

### ISSUE THREAD

**Issue by philibeur** [yogeshpaliyal/KeyPass#3]

**Comment by moriel5** [comment]
This may or may not be covered by issue #2, since I was talking about the underlying database scheme.

**Comment by philibeur** [comment]
Indeed, I did not take the time to check, I was too enthusiastic about your project.

**Comment by moriel5** [comment]
I understand, however I am not the author, that would be @yogeshpalial.

**Comment by yogeshpaliyal** [comment]
This is just the initial release, we can add great features and improve it lot with community support
Thanks for you feedbacks @moriel5 @philibeur
