### ISSUE TITLE
crypto donation (feature req.)

### ISSUE THREAD

**Issue by Wjxfi** [yogeshpaliyal/KeyPass#332]
xmr (privacy) or usdt (stability and popularity) or dai (improved usdt) the best option

**Comment by yogeshpaliyal** [comment]
I don't use any crypto wallet, can you suggest any? @Wjxfi

**Comment by yogeshpaliyal** [comment]
Cool, registered on agoradesk

**Comment by yogeshpaliyal** [comment]
Here is the monero address 
```
87LPBVjAqJRH8Pj4UYyHJAMLPssvp2Y5tBsVtNoJtHb3TB2rhPCBi3yawWfnNC4EfEKkm1pafssRw8PLczGWg3BPUtMopEu
```

**Comment by yogeshpaliyal** [comment]
Thanks @Wjxfi
