### ISSUE TITLE
Migrate to Jetpack Compose

### ISSUE THREAD

**Issue by yogeshpaliyal** [yogeshpaliyal/KeyPass#34]
## Pages to Migrate
- [x] Dashboard
- [x] HomeFragment
- [x] Detail Page
- [x] Settings Page
- [x] Create TOTP 
- [x] Generate Password
- [x] Auth Page

**Comment by t-regbs** [comment]
I would like to work on it. I wanted to know how exactly you prefer to do it.
Maybe migrating parts of the app to compose gradually (eg. screen by screen)?
But then I can see a keypasscompose module, was wondering what your plan was with that?

**Comment by yogeshpaliyal** [comment]
Yeah, so actual plan is to keep app in both frameworks

**Comment by t-regbs** [comment]
ok I see
with a shared common module
what would you suggest todo first?

**Comment by yogeshpaliyal** [comment]
Shared common module contains all the logic, except for the UI, that can be used with both XML and compose.

**Comment by 5AbhishekSaxena** [comment]
What is the name of the stable branch for compose?

**Comment by yogeshpaliyal** [comment]
composeUpdate branch

**Comment by 5AbhishekSaxena** [comment]
Do you have any plans for the migration?

**Comment by yogeshpaliyal** [comment]
@5AbhishekSaxena no there is no plan as such, we can go screen by screen, first homepage, then add account page.

**Comment by 5AbhishekSaxena** [comment]
@yogeshpaliyal cool, let's create the issues and start working.

**Comment by 5AbhishekSaxena** [comment]
Why do you have a separate module for Compose?

**Comment by yogeshpaliyal** [comment]
Because I don't want to break the App while we migrate to XML and also we can keep XML module so others can go through code of XML and Compose both.

**Comment by 5AbhishekSaxena** [comment]
You can have compose code in xml and vice versa and it won't break anything as it is built that way.

You can refer to the official documentation for more information. Link: https://developer.android.com/jetpack/compose/interop/migration-strategy

I have also written an article on the migration that you can refer to as well. Link: https://proandroiddev.com/migration-to-jetpack-compose-for-a-legacy-application-3bf256df2ebe

**Comment by yogeshpaliyal** [comment]
Yes I am aware of that but I want to keep both the apps, we can do one thing in compose we can copy xml code and then migrate this to compose.

**Comment by 5AbhishekSaxena** [comment]
Okay. It would be great if you could do the basic setup to begin the migration.

**Comment by yogeshpaliyal** [comment]
Sure I will do the basic setup

**Comment by yogeshpaliyal** [comment]
basic setup done for compose module
