### ISSUE TITLE
Add Strong Biometric Security on Sign in

### ISSUE THREAD

**Issue by santigandolfo** [yogeshpaliyal/KeyPass#341]
**Is your feature request related to a problem? Please describe.**
I'd like to have a separate PIN (or no pin at all) when signing into the app in order to use strong biometric security instead of the default device credentials.

In the current implementation, if someone is shoulder surfing and then steals your phone, then they can also enter into the app (because the app uses DEVICE_CREDENTIAL instead of BIOMETRIC_STRONG) with the phone pin/pattern.

**Describe the solution you'd like**
Add BIOMETRIC_STRONG biometric login.

**Describe alternatives you've considered**
-

**Additional context**

**Comment by yogeshpaliyal** [comment]
Thanks @santigandolfo for raising this, will look into this.

**Comment by yogeshpaliyal** [comment]
Custom password is implemented, merged in master will be available in the next version.
