### ISSUE TITLE
The app doesn't work with phones that don't have biometrics

### ISSUE THREAD

**Issue by n00xbg** [yogeshpaliyal/KeyPass#439]
I use Version 1.4.9 downloaded from F-Droid

When I open the app and click the "Enter to KeyPass" button, it says "Authentication error: Biometric hardware unavailable"

1. Open the app
2. Click on "Enter to KeyPass" button
3. See the result

**Expected behavior**
I expect to enter the app

**Screenshots**
![Screenshot_20230408_202326_com yogeshpaliyal keypass](https://user-images.githubusercontent.com/127140061/230735269-0649f469-2a82-47d5-9bf5-8fa13080487e.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei Y5p
 - OS: Android 10
 

![vers](https://user-images.githubusercontent.com/127140061/230735338-5613d46b-dd7b-4074-8e6a-4c917ef14ac9.png)

**Comment by yogeshpaliyal** [comment]
Added custom password screen #480  in releasee
