### ISSUE TITLE
Multiple setting page

### ISSUE THREAD

**Issue by ssnaruka** [yogeshpaliyal/KeyPass#477]
**Describe the bug**
Creating multiple setting tab.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Settings icon multiple time'
3. See error

**Expected behavior**
If user already on setting tab then not create any other instance.

**Comment by yogeshpaliyal** [comment]
@ssnaruka would you like to work on this?

**Comment by ssnaruka** [comment]
@yogeshpaliyal Yes

**Comment by yogeshpaliyal** [comment]
@ssnaruka Any update on this?

**Comment by rohitashwani1** [comment]
@yogeshpaliyal Can I work on this issue ??

**Comment by yogeshpaliyal** [comment]
@rohitashwani1 yes sure

**Comment by rohitashwani1** [comment]
I have resolved the mentioned issue and I have created a pull request #522 .

**Comment by yogeshpaliyal** [comment]
Thanks @rohitashwani1 ♥️
