### ISSUE TITLE
Biometric unlock feature not working 

### ISSUE THREAD

**Issue by Sureshgorai25** [yogeshpaliyal/KeyPass#556]
The biometric unlock feature is not working in my Device, when I go to settings and then unlock with biometric and tap on it nothing happens.
Please fix this issue

**Comment by yogeshpaliyal** [comment]
Is it showing enable disable in the biometric option? What is the text below the biometric option.

**Comment by Sureshgorai25** [comment]
Reinstalling the app worked, earlier it was only showing disabled even after tapping several times.
Thanks
