### ISSUE TITLE
`ACCESS_NETWORK_STATE` permission

### ISSUE THREAD

**Issue by shuvashish76** [yogeshpaliyal/KeyPass#557]
> _Complete Offline : No internet permission has been added._

Here is the result from [AM](https://github.com/MuntashirAkon/AppManager) Manifest Viewer : `android.permission.ACCESS_NETWORK_STATE`

From F:Droid
![KeyPass](https://github.com/yogeshpaliyal/KeyPass/assets/48226312/43f47ee8-5502-44c7-8342-df9602fa12d7)

Probably [Work Manager](https://github.com/androidx/androidx/blob/a0bdf69e05e587fde2d8ddd3140bfbe46fea5702/work/work-runtime/src/main/AndroidManifest.xml#L21) is the culprit here.

App version : `1.4.14`

**Comment by yogeshpaliyal** [comment]
Thanks for reporting this, will try to remove this
