### ISSUE TITLE
QR Code Support

### ISSUE THREAD

**Issue by Tanmandal** [yogeshpaliyal/KeyPass#559]
Please add the feature of sharing account information through QRCode including all information(of that particular account) saved in keepass 
It would be very handy for non-digital password backup
The QRCode of several accounts could be printed for emergencies

**Comment by Dkingofcode** [comment]
Can i be assigned this issue? If there are any resources that can help in completing the task pls i would like to know.

**Comment by yogeshpaliyal** [comment]
There is no resources as of now

**Comment by divyampahujaa** [comment]
Hi @yogeshpaliyal, can I work on this issue if nobody is assigned yet ?

**Comment by yogeshpaliyal** [comment]
Sure @divyampahujaa
