### ISSUE TITLE
Done?

### ISSUE THREAD

**Issue by Wjxfi** [yogeshpaliyal/KeyPass#577]
![8cf871fa-bd98-42a5-be7b-01345e05aaf1.jpg](https://github.com/yogeshpaliyal/KeyPass/assets/113500363/0975ece4-5e5a-4c1a-b125-05e340b3135e)

**Comment by yogeshpaliyal** [comment]
Sorry, didn't get this

**Comment by yogeshpaliyal** [comment]
Not yet 100% done

**Comment by yogeshpaliyal** [comment]
TOTP screen still pending migration on Compose
