### ISSUE TITLE
Change password length default value

### ISSUE THREAD

**Issue by Turhvjbufv** [yogeshpaliyal/KeyPass#594]
When you generate passwords you can change the length of the password but it reverts back to 10 after you go out of the menu, I would like it to stay to what I changed instead of changing back to 10(or at least option in the settings to decide the default to another number)

**Comment by yogeshpaliyal** [comment]
@vladlessi assigning this to you. and Thanks for the contribution

**Comment by yogeshpaliyal** [comment]
@vladleesi can you comment here once, so I can assign it to you

**Comment by vladleesi** [comment]
Sure

**Comment by yogeshpaliyal** [comment]
Thanks @Turhvjbufv for raising this issue and thanks @vladleesi for Improving KeyPass. ❤️
