### ISSUE TITLE
KeyPass does not securely handle credential storage

### ISSUE THREAD

**Issue by BenEdridge** [yogeshpaliyal/KeyPass#618]
**Describe the bug**

Hi there, always great to see more Apps making use of F-Droid! I thought I'd take a quick look due to the popularity.

I believe KeyPass in it's current status does not meet the security standards of other password managers or the recommendations by organisations such as OWASP and MITRE. This project should probably contain a warning on usage and details on encryption mechanisms so users can make an informed choice on on how their sensitive data is protected.

**Issues**

1. The current database (storing passwords) and shared preferences (storing the login password) are are not encrypted and thus accessible in plaintext to potential attackers without logging in.
2.  Database backups use a static IV of: `private val iV = byteArrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)` and when encrypted this results in a more predictable and potentially vulnerable exported backup.

**To Reproduce**

1. Download source code.
2. Build and then run on an emulator or real device with debugging enabled.
3. Open KeyPass then create a password to access.
5. Create a few example accounts.
6. Run `adb shell "run-as com.yogeshpaliyal.keypass cat /data/data/com.yogeshpaliyal.keypass/databases/KeyPass-wal" > data.db` to save the Write Ahead Log file containing the most recent changes to the DB.
7. `cat data.db`

Leak of login password
![image](https://github.com/yogeshpaliyal/KeyPass/assets/8308258/b34d425b-08bc-440f-8579-cd22eb3979f7)

Leak of accounts
![image](https://github.com/yogeshpaliyal/KeyPass/assets/8308258/c4eb15ef-9609-48ce-bb8b-eff5f6ca1dc3)

**Recommendations**

- Enhance and fix the current storage mechanisms referring to the Android MASTG recommendations: https://github.com/OWASP/owasp-mastg/blob/master/Document/0x05d-Testing-Data-Storage.md

**Comment by yogeshpaliyal** [comment]
Thanks @BenEdridge for raising this, will address these ASAP

**Comment by yogeshpaliyal** [comment]
@BenEdridge Security has been improved in the latest version, can you verify once, thanks once again for raising this. ❤️

**Comment by BenEdridge** [comment]
Hi @yogeshpaliyal I've taken a quick look. Much better than before but one issue I raised still remains.

Static IV use (This should be generated with secure random number generator) and stored alongside encrypted data. Then upon upon decryption and utilised during decryption functionality.
```
common/src/main/java/com/yogeshpaliyal/common/dbhelper/EncryptionHelper.kt
32:    private val iV = byteArrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
``` 

Additionally, user chosen passwords should be used to derive a secure encryption key using PBKDF2 or Argon2 (Similar to what 1Password and Bitwarden does). 

User password -> PBKDF2/Argon2 -> Database Encryption/Database Backup Encryption

**Comment by yogeshpaliyal** [comment]
Sure will look into this, thanks
