### ISSUE TITLE
Authentication returns to home page

### ISSUE THREAD

**Issue by Zozosticot** [yogeshpaliyal/KeyPass#639]
**Describe the bug**

Entering the password or fingerprint returns you to the phone's home page. The app remains in the background, but returning to it leaves me on the authentication page.

**To Reproduce**
1. Open the app
2. Enter the right password or fingerprint

**Expected behavior**

The application closes suddenly and is considered a minimized application.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A23 5G
 - OS: Android 13, One UI 5.1
 - FDroid 1.16.4
 - KeyPass 1.4.18

**Additional context**

I can't downshift to Fdroid either

**Comment by mori-oh** [comment]
I reproduced it by upgrading from version 1.4.17 to version 1.4.18.

procedure

1. Install 1.4.17 on F-droid.
2. Upgrade from 1.4.17 to 1.4.18 with F-droid.

**Comment by yogeshpaliyal** [comment]
Thanks for reporting this, working on it
