### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by TeaqariaWTF** [yogeshpaliyal/KeyPass#640]
Hi, 
Android 13
ArrowOS
App version : 1.4.18

I open the app and enter my password and the app crashes.
I'm leaving a log here. Hope it helps

[keypass.txt](https://github.com/yogeshpaliyal/KeyPass/files/12198149/keypass.txt)

**Comment by yogeshpaliyal** [comment]
Thanks for reporting this, working on it
