### ISSUE TITLE
All Crashes After Entering Password

### ISSUE THREAD

**Issue by dongltron** [yogeshpaliyal/KeyPass#643]
**Describe the bug**
Just installed, typed password, typed again to confirm, upon clicking Next the app crashes. Opening the app again shows the Enter Password screen as if it's confirmed the password and just wants me to log in now. App crashes upon hitting Next after entering password.

**To Reproduce**
1. Type password.
2. Next
3. Error

**Expected behavior**
Let me log in and set up app

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 13
 - Version: Latest

**Additional context**
Maybe has something to do with the latest Pixels only supporting 64 bit? I imagine it wouldn't let me launch it at all though, if that was the case. I dunno.

**Comment by yogeshpaliyal** [comment]
This crash has been fixed in latest version, will be available soon on F-droid sorry for the inconvenience.
