### ISSUE TITLE
1.4.18 crashing at launch on android 13 (graphene) pixel 6 pro

### ISSUE THREAD

**Issue by deanaba** [yogeshpaliyal/KeyPass#644]
**Describe the bug**
Application crashes after correct password is entered.
**To Reproduce**
1. Pixel 6 Pro Android 13 Graphene build TQ3A.230705.001.2023072600
2. Install (or update) Keypass 1.4.18 via fdroid.
3. Launch app, enter correct password
4. click continue
Expect to get to password list but instead app crashes. No error given.
Replicated when upgrading from 1.4.17
as well as clean install.
Note entering incorrect password, app warns user. Crash only occurs after entering correct app password.
Removing app, reinstalling 1.4.17 and restoring from backup was only way for me to get passwords back.

**Comment by yogeshpaliyal** [comment]
The issue has been resolved in latest build v1.4.19 and eill be rolled out soon to F-droid

**Comment by c-key** [comment]
I can open the app as normal with version 1.4.19. But all saved data is lost! Why? Is this a bad joke?
Any chance to get the data back without root?

**Comment by yogeshpaliyal** [comment]
You can only get data back if you have took any backup
