### ISSUE TITLE
When launching an application, an error always pops up, unable to launch the application

### ISSUE THREAD

**Issue by Wjxfi** [yogeshpaliyal/KeyPass#652]
When launching an application, an error always pops up, unable to launch the application

after a few new updates. Version 1.4.19

Before some updates everything worked - then it didn't. In f-droid

**Screenshots**
![6a64cdbe-82ba-4a25-9447-e477e91463e1.jpg](https://github.com/yogeshpaliyal/KeyPass/assets/113500363/4f940581-208e-41f4-b264-e4cdaca68c1a)

![ce29c508-0057-4513-a0a4-3f9c1ba79cc5.jpg](https://github.com/yogeshpaliyal/KeyPass/assets/113500363/24b1c45f-2b9a-4536-9c8e-8c75ced1abe3)

**Smartphone (please complete the following information):**
 - 
 - OS: [e.g. iOS8.1] android 13, miui 13.0.5

**Additional context**

**Comment by yogeshpaliyal** [comment]
Can you please uninstall and reinstall the app to check if it is working

**Comment by yogeshpaliyal** [comment]
If you make a Titanium backup of the app+data, then delete the app, install Version 1416 or 1417 (Thanks to F-Droid for storing old revisions), restore the backup. Open the app, it will error you out. Then reinstall 1419 and it will open as normal.

Thanks to Anthony Walls Jr for the workaround

**Comment by kizm0** [comment]
is there no workaround except reinstalling the app? i do have a backup but there are some TOTPs missing...

**Comment by yogeshpaliyal** [comment]
There is no workaround

**Comment by DocShadrach** [comment]
The same here. If I reinstall the app it works for a while and then it returns to the same error.

**Comment by yogeshpaliyal** [comment]
Can anyone please share the process to replicate it, it would be a great help.

**Comment by DocShadrach** [comment]
Hi. There is no process, this happens as soon as the app is opened.

**Comment by yogeshpaliyal** [comment]
I am not able to replicate this, tried various things, but not able to replicate it.

**Comment by DocShadrach** [comment]
I don't know what can I do. Here's a video

https://drive.google.com/file/d/1vEgQJzJX6zvpEy_Ns876omFDxACcJHQC/view?usp=drivesdk

**Comment by DocShadrach** [comment]
Maybe we can downgrade to a version without this error, I will try...

**Comment by DocShadrach** [comment]
Now I'm with version 1.4.16, working fine for now. I tell you in a couple of days...

**Comment by yogeshpaliyal** [comment]
Thanks @DocShadrach 
Can anyone please test the crash on the latest version v1.4.20.

**Comment by DocShadrach** [comment]
Where I can get the apk of that version? It's not in PlayStore nor in F-Droid yet..

**Comment by yogeshpaliyal** [comment]
Uploading it on playstore as beta build, can you sign up for beta?

**Comment by yogeshpaliyal** [comment]
@DocShadrach @Wjxfi 
New build is live on Play store beta channel.

**Comment by DocShadrach** [comment]
Ok. I'm trying 👍 It works for now.

**Comment by yogeshpaliyal** [comment]
Thanks @DocShadrach 
These were the replication steps on older builds.

The steps were fresh install, make any acc with a passwoed, then enable backups and fingerprint. Close out of app, then reopen it and it will force crash every time.

**Comment by DocShadrach** [comment]
Working fine for now 👍

**Comment by yogeshpaliyal** [comment]
This issue has been resolved in v1.4.20 and by PR #668 .

Thanks Everyone for reporting this and helping us to find and resolve the bug. 🙌🙌
