### ISSUE TITLE
Exception while launch app

### ISSUE THREAD

**Issue by xixiwai0819** [yogeshpaliyal/KeyPass#676]
**Describe the bug**
When launching an application, an error always pops up, unable to launch the application

**To Reproduce**
1. migrate app from an old phone
2. enable fingerprint on new phone
3. launch app

**Expected behavior**
no crash

**Screenshots**
![image](https://github.com/yogeshpaliyal/KeyPass/assets/129244507/14f3f8d9-1fb5-4460-aa02-420d805e8735)

**Smartphone (please complete the following information):**
 - Device: [mix fold 3]
 - OS: [Android 13]
 - APP Version: [1.4.20]

**Comment by yogeshpaliyal** [comment]
Have you migrated from v1.4.19 or v1.4.18

**Comment by yogeshpaliyal** [comment]
Fixed the crash in v1.4.21, but if you updated the app from older versions, and still facing the crash you have to clear app data, then it will work as expected, sorry for the inconvienience.
