### ISSUE TITLE
Restore-key

### ISSUE THREAD

**Issue by ghost** [yogeshpaliyal/KeyPass#8]
While creating a backup keypass itself creates me a key inorder to restore the backup and this way i was forced to store the key somewhere else and there will be chances that i might loose it.
It will be a bit convenient if i could choose the key.

**Comment by yogeshpaliyal** [comment]
@Avinash-Lvs if you choose the key, then there is chances that you pick a key that is common or may be easily guessable.

**Comment by Avinash-Lvs** [comment]
Hmm, thats right too.

**Comment by Avinash-Lvs** [comment]
But an alternative option would be great. Leaving us with the choice to make, generated key or key of choice.

**Comment by yogeshpaliyal** [comment]
Added the option to set a custom keyphrase for backups
https://github.com/yogeshpaliyal/KeyPass/pull/252
