### ISSUE TITLE
Add description on create password

### ISSUE THREAD

**Issue by bhagirathpaliyal** [yogeshpaliyal/KeyPass#818]
.

**Comment by kapilBaser** [comment]
Can you explain this issue or it is closed? @bhagirathpaliyal @yogeshpaliyal

**Comment by yogeshpaliyal** [comment]
We have to add description on page where we ask user to create password, there we should add a proper description

**Comment by kapilBaser** [comment]
But we already have notes in create password page.

**Comment by kapilBaser** [comment]
What is the use of that description in application?

**Comment by yogeshpaliyal** [comment]
Description should be something like "This password will be used to open the app in future"

**Comment by kapilBaser** [comment]
Okay, I will do it!

**Comment by yogeshpaliyal** [comment]
Added in #871
