### ISSUE TITLE
Scan password from QR, parse more information from otpauth URL when scanning TOTP QR code

### ISSUE THREAD

**Issue by eldad** [yogeshpaliyal/KeyPass#91]
Hi Yogesh,

Thank you so much for KeyPass, I found it on F-Droid and I've been using it for a while.

I have two suggestions around QR code scanning, and I already implemented these in my private fork.

1. When adding a password via QR code, it is convenient and a bit more secure to directly scan. Previously I used a QR scanner and copied the password through Android clipboard.
> https://github.com/eldad/KeyPass/commit/57bbbc07eb28fbd0113643d237d718f040d8b243

2. When scanning a TOTP, it's nice to also have the label parsed and autofilled.
> https://github.com/eldad/KeyPass/compare/5f19b3eb31c07b6efdc318e9a7cd7b82ed4fbe50..a80ac16e6449a5eb4ad679bab8ce779827d8db1f

I saw that you're in the middle of some refactoring (my work is based off 1.4.1), so it's not compatible with your current master.
If you'd prefer, I can open a PR on the latest version.

Cheers,
Eldad

**Comment by yogeshpaliyal** [comment]
Thanks you for your valuable feedbacks.
Yes, please make a PR so I can verify and merge that
